site_name: "SimpleDialogue"
site_url: https://crabzzai.github.io/simpledialogue/
site_description: A dialogue system for Roblox games
repo_url: https://github.com/crabzzai/simpledialogue
repo_name: crabzzai/simpledialogue

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - search.highlight
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Basic Usage: getting-started/basic-usage.md
  - API Reference:
    - Core API: api/core.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true
